# Generated by Django 3.0.5 on 2021-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
