# Generated by Django 3.0.5 on 2021-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='donor',
            name='nic',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
